# Generated by Django 5.2.3 on 2025-11-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("english", "English"), ("hindi", "Hindi")],
                        default="english",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
