# Generated by Django 5.2.3 on 2025-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translating",
            name="eng_count",
        ),
        migrations.RemoveField(
            model_name="translating",
            name="hin_count",
        ),
        migrations.AddField(
            model_name="translating",
            name="translated_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
