# Generated by Django 5.2.3 on 2025-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0002_remove_translating_eng_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translating",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
